```{r}
library(RMeCab)
library(igraph)
# install.packages("doBy")
library(doBy) # which.maxn
library(dplyr) # filter
```


```{r}
remarks_df = read.csv("./demo1-1.csv")

raw_mor = list()
morphenes = list()
for(r in remarks_df$remark) {
  mor = RMeCabC(r, 1)
  morphenes = append(morphenes, list(mor[names(unlist(mor)) == "名詞" | names(unlist(mor)) == "動詞" | names(unlist(mor)) == "形容詞"])) 
  raw_mor = append(raw_mor, list(mor))
}

adjacency_df <- data.frame(matrix(0, length(morphenes), length(morphenes)))
for (i in 1:length(morphenes)) {
  r1 <- unlist(morphenes[i])
  for (j in i+1:length(morphenes)) {
    inte <- intersect(r1, unlist(morphenes[j]))
    if (length(inte) > 0) {
      adjacency_df[i, j] = length(inte)
    }
  }
}

net <- graph_from_adjacency_matrix(as.matrix(adjacency_df) , mode="directed")

plot(net, vertex.size = 3, vertex.label = NA, edge.arrow.size=.2, edge.width=.4, edge.curved=.1) #1

bt = betweenness(net)
deg = degree(net, mode="out")

remarks_bt_df = remarks_df
remarks_bt_df$betweenness = bt
remarks_deg_df = remarks_df
remarks_deg_df$degree = deg

which.maxn(bt, n=10)
which.maxn(deg, n=10)

attendees = unique(remarks_df$attendee)

for (a in attendees) {
  target_bw_df = filter(remarks_bt_df, attendee == a)
  plot(target_bw_df$index, target_bw_df$betweenness, type="b", col="royalblue3", pch=15, cex=2, lwd=2, lty=1)
  title(paste("Betweeness: ", a))
}

for (a in attendees) {
  target_deg_df = filter(remarks_deg_df, attendee == a)
  plot(target_deg_df$index, target_deg_df$degree, type="b", col="royalblue3", pch=15, cex=2, lwd=2, lty=1)
  title(paste("OutDegree: ", a))
}
```


```{r}
# 模範回答情報から, 期待単語辞書(answer_morphenes_list)を作成

answer_reason_list = read.csv("./answer_demo1.csv")$reason
answer_morphenes_list = c()
for(r in answer_reason_list){
  mor = RMeCabC(r, 1)
  answer_morphenes_list = c(answer_morphenes_list, mor[names(unlist(mor)) == "名詞" | names(unlist(mor)) == "動詞" | names(unlist(mor)) == "形容詞"])
}

# answer_morphenes_list
```

```{r}
# test!!!!!!!!!!!!!!
# unlist(morphenes[1])
# intersect(unlist(morphenes[1]), answer_morphenes_list)
```

```{r}
remarks_df = read.csv("./demo1-1.csv")

raw_mor = list()
morphenes = list()
for(r in remarks_df$remark) {
  mor = RMeCabC(r, 1)
  morphenes = append(morphenes, list(mor[names(unlist(mor)) == "名詞" | names(unlist(mor)) == "動詞" | names(unlist(mor)) == "形容詞"])) 
  raw_mor = append(raw_mor, list(mor))
}

adjacency_df <- data.frame(matrix(0, length(morphenes), length(morphenes)))
tmp = list()
for (i in 1:length(morphenes)) {
  r1 <- unlist(morphenes[i]) 
  im = list()
  for (j in i+1:length(morphenes)) {
    inte <- intersect(r1, unlist(morphenes[j]))
    inte <- intersect(inte, answer_morphenes_list)
    if (length(inte) > 0) {
      adjacency_df[i, j] = length(inte)
      im = append(im, inte)
    }
  }
  tmp = append(tmp, list(im))
}

net <- graph_from_adjacency_matrix(as.matrix(adjacency_df) , mode="directed")

plot(net, vertex.size = 3, vertex.label = NA, edge.arrow.size=.2, edge.width=.4, edge.curved=.1) #1

bt = betweenness(net)
deg = degree(net, mode="out")

remarks_bt_df = remarks_df
remarks_bt_df$betweenness = bt
remarks_deg_df = remarks_df
remarks_deg_df$degree = deg

attendees = unique(remarks_df$attendee)

important_remarks_index = c()
for (a in attendees) {
  target_bw_df = filter(remarks_bt_df, attendee == a)
  plot(target_bw_df$index, target_bw_df$betweenness, type="b", col="royalblue3", pch=15, cex=2, lwd=2, lty=1)
  title(paste("Betweeness: ", a))
  imp = target_bw_df[which.max(target_bw_df$betweenness),]$index
  print(paste(a, imp))
  important_remarks_index = c(important_remarks_index, imp)
}

for (a in attendees) {
  target_deg_df = filter(remarks_deg_df, attendee == a)
  plot(target_deg_df$index, target_deg_df$degree, type="b", col="royalblue3", pch=15, cex=2, lwd=2, lty=1)
  title(paste("OutDegree: ", a))
  imp = target_deg_df[which.max(target_deg_df$degree),]$index
  print(paste(a, imp))
  important_remarks_index = c(important_remarks_index, imp)
}
```

```{r}
tei_bw_df = filter(remarks_bt_df, attendee=="程")
tei_bw_df
```


```{r}
important_df = filter(remarks_df, index %in% important_remarks_index)
print(important_df)
for(i in 1:nrow(important_df)){
  ind = important_df[i,]$index
  print(i)
  print(table(unlist(tmp[ind])))
}
```
```{r}
analyze_proto = function(path){
  remarks_df = read.csv(path)
  
  raw_mor = list()
  morphenes = list()
  for(r in remarks_df$remark) {
    mor = RMeCabC(r, 1)
    morphenes = append(morphenes, list(mor[names(unlist(mor)) == "名詞" | names(unlist(mor)) == "動詞" | names(unlist(mor)) == "形容詞"])) 
    raw_mor = append(raw_mor, list(mor))
  }
  
  adjacency_df <- data.frame(matrix(0, length(morphenes), length(morphenes)))
  for (i in 1:length(morphenes)) {
    r1 <- unlist(morphenes[i])
    for (j in i+1:length(morphenes)) {
      inte <- intersect(r1, unlist(morphenes[j]))
      if (length(inte) > 0) {
        adjacency_df[i, j] = length(inte)
      }
    }
  }
  
  net <- graph_from_adjacency_matrix(as.matrix(adjacency_df) , mode="directed")
  
  plot(net, vertex.size = 3, vertex.label = NA, edge.arrow.size=.2, edge.width=.4, edge.curved=.1) #1
  
  bt = betweenness(net)
  deg = degree(net, mode="out")
  
  remarks_bt_df = remarks_df
  remarks_bt_df$betweenness = bt
  remarks_deg_df = remarks_df
  remarks_deg_df$degree = deg
  
  which.maxn(bt, n=10)
  which.maxn(deg, n=10)
  
  attendees = unique(remarks_df$attendee)
  
  for (a in attendees) {
    target_bw_df = filter(remarks_bt_df, attendee == a)
    plot(target_bw_df$index, target_bw_df$betweenness, type="b", col="royalblue3", pch=15, cex=2, lwd=2, lty=1)
    title(paste("Betweeness: ", a))
  }
  
  for (a in attendees) {
    target_deg_df = filter(remarks_deg_df, attendee == a)
    plot(target_deg_df$index, target_deg_df$degree, type="b", col="royalblue3", pch=15, cex=2, lwd=2, lty=1)
    title(paste("OutDegree: ", a))
  }
}
```

```{r}
analyze = function(path) {
  remarks_df = read.csv(path)
  raw_mor = list()
  morphenes = list()
  for(r in remarks_df$remark) {
    mor = RMeCabC(r, 1)
    morphenes = append(morphenes, list(mor[names(unlist(mor)) == "名詞" | names(unlist(mor)) == "動詞" | names(unlist(mor)) == "形容詞"])) 
    raw_mor = append(raw_mor, list(mor))
  }

  adjacency_df <- data.frame(matrix(0, length(morphenes), length(morphenes)))
  tmp = list()
  for (i in 1:length(morphenes)) {
    r1 <- unlist(morphenes[i]) 
    im = list()
    for (j in i+1:length(morphenes)) {
      inte <- intersect(r1, unlist(morphenes[j]))
      inte <- intersect(inte, answer_morphenes_list)
      if (length(inte) > 0) {
        adjacency_df[i, j] = length(inte)
        im = append(im, inte)
      }
    }
    tmp = append(tmp, list(im))
  }

  net <- graph_from_adjacency_matrix(as.matrix(adjacency_df) , mode="directed")

  plot(net, vertex.size = 3, vertex.label = NA, edge.arrow.size=.2, edge.width=.4, edge.curved=.1) #1

  bt = betweenness(net)
  deg = degree(net, mode="out")

  remarks_bt_df = remarks_df
  remarks_bt_df$betweenness = bt
  remarks_deg_df = remarks_df
  remarks_deg_df$degree = deg

  attendees = unique(remarks_df$attendee)
  
  important_remarks_index = c()
  for (a in attendees) {
    target_bw_df = filter(remarks_bt_df, attendee == a)
    plot(target_bw_df$index, target_bw_df$betweenness, type="b", col="royalblue3", pch=15, cex=2, lwd=2, lty=1)
    title(paste("Betweeness: ", a))
  }
  
  for (a in attendees) {
    target_deg_df = filter(remarks_deg_df, attendee == a)
    plot(target_deg_df$index, target_deg_df$degree, type="b", col="royalblue3", pch=15, cex=2, lwd=2, lty=1)
    title(paste("OutDegree: ", a))
  }
  for(a in attendees){
    tar_df = filter(remarks_bt_df, attendee==a)
    tar_df = filter(tar_df, betweenness>0)
    print(paste(a, mean(tar_df$betweenness)))
  }
}

```

```{r}
analyze_proto("./demo1-2.csv")
```

```{r}
analyze("./demo1-2.csv")
```

```{r}
analyze("./data/demo1-1.csv")
```


```{r}
analyze("./demo1-2.csv")
```

