```{r}
answer_morphenes_list = scan("./answer_like_morphenes.txt", character(), quote = "")
attendees = c("後藤", "佐野", "鳥越")
attendees_prefixes = list("後藤"="got", "佐野"="san", "鳥越"="tor")
postfixes = c("pre", "mid", "pos")
ans_df = read.csv("./answers/answer.csv")
```

```{r}
df = analyze_df(attendees, create_kyoki_net("./remarks/exp2-1.csv"))
df2 = analyze_df(attendees, create_kyoki_net("./remarks/exp2-2.csv"))
exp1 = analyze_df(attendees, create_kyoki_net_from_df(merge_df_from_path("./remarks/exp2-1.csv", "./remarks/exp2-2.csv")))

qa_df = analyze_df(attendees, create_kyoki_net("./remarks/exp2-1-qa-joined.csv"))
qa_df_2 = analyze_df(attendees, create_kyoki_net("./remarks/exp2-2-qa-joined.csv"))
qa_exp1 = analyze_df(attendees, create_kyoki_net_from_df(merge_df_from_path("./remarks/exp2-1-qa-joined.csv", "./remarks/exp2-2-qa-joined.csv")))
```

```{r}
prefix = c("got", "san", "tor")
suffix = c("pre", "mid", "pos")
damerau_right = analyze_damerau_right_exp("./answers", prefix, suffix)
damerau_right_las = analyze_damerau_right_las_exp("./answers", prefix, suffix)

conv(df, df2)
conv(qa_df, qa_df_2)
conv_ans(damerau_right_las)
conv_ans(damerau_right)
calculate_cor(df, exp1, damerau_right_las)
calculate_cor(qa_df, qa_exp1, damerau_right_las)
calculate_cor(df, df2, damerau_right)
calculate_cor(qa_df, qa_df_2, damerau_right)
df
```

```{r}
right = analyze_right("./answers", prefix, suffix)
right_las = analyze_right2("./answers", prefix, suffix)
calculate_cor(df, exp1, right_las)
calculate_cor(qa_df, qa_exp1, right_las)
calculate_cor(df, df2, right)
calculate_cor(qa_df, qa_df_2, right)
```

